# Generated by Django 5.2.5 on 2025-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Прізвище')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
        ),
    ]
